// Patrones de movimiento con metadatos visuales
export const PATS = {
  empuje:   {label:"EMPUJE",           labelEn:"PUSH",        color:"#60a5fa", icon:"💪"},
  traccion: {label:"TRACCION",         labelEn:"PULL",        color:"#a78bfa", icon:"🔙"},
  rodilla:  {label:"RODILLA DOM.",     labelEn:"KNEE DOM.",   color:"#4ade80", icon:"🦵"},
  bisagra:  {label:"BISAGRA CADERA",   labelEn:"HIP HINGE",  color:"#f87171", icon:"⬇️"},
  core:     {label:"CORE",             labelEn:"CORE",        color:"#facc15", icon:"🎯"},
  movilidad:{label:"MOVILIDAD",        labelEn:"MOBILITY",    color:"#fb923c", icon:"🌀"},
  cardio:   {label:"CARDIO",           labelEn:"CARDIO",      color:"#34d399", icon:"🏃"},
  pierna:   {label:"PIERNA",           labelEn:"LEGS",        color:"#4ade80", icon:"🦵"},
  movil:    {label:"MOVILIDAD",        labelEn:"MOBILITY",    color:"#fb923c", icon:"🌀"},
};

// Biblioteca de ejercicios
export const EX = [
  {id:"sq",    name:"Sentadilla Barra",   nameEn:"Barbell Squat",    pattern:"pierna",  muscle:"Cuadriceps",         equip:"Barra"},
  {id:"lp",    name:"Prensa Piernas",     nameEn:"Leg Press",        pattern:"pierna",  muscle:"Cuadriceps/Gluteo",  equip:"Maquina"},
  {id:"lunge", name:"Zancada",            nameEn:"Lunge",            pattern:"pierna",  muscle:"Cuadriceps",         equip:"Mancuernas"},
  {id:"dl",    name:"Peso Muerto",        nameEn:"Deadlift",         pattern:"pierna",  muscle:"Isquios/Gluteo",     equip:"Barra"},
  {id:"rdl",   name:"PM Rumano",          nameEn:"Romanian DL",      pattern:"pierna",  muscle:"Isquios/Gluteo",     equip:"Barra"},
  {id:"hcurl", name:"Curl Femoral",       nameEn:"Leg Curl",         pattern:"pierna",  muscle:"Isquios",            equip:"Maquina"},
  {id:"hip",   name:"Hip Thrust",         nameEn:"Hip Thrust",       pattern:"pierna",  muscle:"Gluteos",            equip:"Barra"},
  {id:"calf",  name:"Pantorrillas",       nameEn:"Calf Raise",       pattern:"pierna",  muscle:"Gemelos",            equip:"Maquina"},
  {id:"bp",    name:"Press Banca",        nameEn:"Bench Press",      pattern:"empuje",  muscle:"Pecho",              equip:"Barra"},
  {id:"ibp",   name:"Press Inclinado",    nameEn:"Incline Press",    pattern:"empuje",  muscle:"Pecho Alto",         equip:"Barra"},
  {id:"dbp",   name:"Press Mancuernas",   nameEn:"DB Bench",         pattern:"empuje",  muscle:"Pecho",              equip:"Mancuernas"},
  {id:"fly",   name:"Aperturas",          nameEn:"Chest Fly",        pattern:"empuje",  muscle:"Pecho",              equip:"Mancuernas"},
  {id:"ohp",   name:"Press Militar",      nameEn:"Overhead Press",   pattern:"empuje",  muscle:"Hombro",             equip:"Barra"},
  {id:"late",  name:"Elev. Lateral",      nameEn:"Lateral Raise",    pattern:"empuje",  muscle:"Hombro Lateral",     equip:"Mancuernas"},
  {id:"dip",   name:"Fondos",             nameEn:"Dips",             pattern:"empuje",  muscle:"Pecho/Triceps",      equip:"Paralelas"},
  {id:"tpush", name:"Ext. Triceps",       nameEn:"Triceps Extension",pattern:"empuje",  muscle:"Triceps",            equip:"Polea"},
  {id:"pu",    name:"Dominadas",          nameEn:"Pull-ups",         pattern:"traccion",muscle:"Dorsal/Biceps",      equip:"Barra fija"},
  {id:"row",   name:"Remo Barra",         nameEn:"Barbell Row",      pattern:"traccion",muscle:"Dorsal",             equip:"Barra"},
  {id:"crow",  name:"Remo Polea",         nameEn:"Cable Row",        pattern:"traccion",muscle:"Dorsal",             equip:"Polea"},
  {id:"lat",   name:"Jalon al Pecho",     nameEn:"Lat Pulldown",     pattern:"traccion",muscle:"Dorsal/Biceps",      equip:"Maquina"},
  {id:"facep", name:"Face Pull",          nameEn:"Face Pull",        pattern:"traccion",muscle:"Hombro Posterior",   equip:"Polea"},
  {id:"curl",  name:"Curl Biceps",        nameEn:"Bicep Curl",       pattern:"traccion",muscle:"Biceps",             equip:"Mancuernas"},
  {id:"plank", name:"Plancha",            nameEn:"Plank",            pattern:"core",    muscle:"Core",               equip:"Peso corporal"},
  {id:"crunch",name:"Crunch",             nameEn:"Crunch",           pattern:"core",    muscle:"Abdominales",        equip:"Peso corporal"},
  {id:"legr",  name:"Elev. Piernas",      nameEn:"Leg Raise",        pattern:"core",    muscle:"Core/Flexores",      equip:"Barra fija"},
  {id:"mob1",  name:"Movilidad Cadera",   nameEn:"Hip Mobility",     pattern:"movil",   muscle:"Cadera",             equip:"Peso corporal"},
  {id:"mob2",  name:"Movilidad Torax",    nameEn:"Thoracic Mobility",pattern:"movil",   muscle:"Columna",            equip:"Foam roller"},
  {id:"suppu", name:"Dominadas Supinas",  nameEn:"Chin-ups",          pattern:"traccion",muscle:"Biceps/Dorsal",      equip:"Barra fija"},
  {id:"hammer",name:"Biceps Martillo",    nameEn:"Hammer Curl",       pattern:"traccion",muscle:"Biceps/Braquial",    equip:"Mancuernas"},
  {id:"legcurl",name:"Sillon Isquios",   nameEn:"Leg Curl Machine",  pattern:"pierna",  muscle:"Isquios",            equip:"Maquina"},
  {id:"legext",name:"Sillon Cuadriceps", nameEn:"Leg Extension",     pattern:"pierna",  muscle:"Cuadriceps",         equip:"Maquina"},
  {id:"trico", name:"Triceps Polea",     nameEn:"Triceps Pushdown",  pattern:"empuje",  muscle:"Triceps",            equip:"Polea"},
  {id:"lateralfly",name:"Vuelos Laterales",nameEn:"Lateral Raises",  pattern:"empuje",  muscle:"Hombro Lateral",     equip:"Mancuernas"},
  // ROTACION TORACICA
  {id:"trot1",  name:"Rot. Torácica Suelo",   nameEn:"Thoracic Rotation Floor",  pattern:"movil", muscle:"Columna Torácica",  equip:"Peso corporal"},
  {id:"trot2",  name:"Rot. Torácica Cuadrupedia", nameEn:"Quadruped T-Spine Rot.", pattern:"movil", muscle:"Columna Torácica",  equip:"Peso corporal"},
  {id:"trot3",  name:"Rot. Torácica Foam",    nameEn:"Foam Roller T-Spine",       pattern:"movil", muscle:"Columna Torácica",  equip:"Foam roller"},
  {id:"trot4",  name:"Rot. Torácica Banda",   nameEn:"Band Thoracic Rotation",    pattern:"movil", muscle:"Columna Torácica",  equip:"Banda"},
  // MOVILIDAD CADERA
  {id:"hipm1",  name:"90/90 Cadera",          nameEn:"90/90 Hip Stretch",         pattern:"movil", muscle:"Cadera/Glúteo",     equip:"Peso corporal"},
  {id:"hipm2",  name:"Apertura Cadera Banda", nameEn:"Band Hip Opener",           pattern:"movil", muscle:"Cadera/Aductores",  equip:"Banda"},
  {id:"hipm3",  name:"Estocada Movilidad",    nameEn:"Deep Lunge Mobility",       pattern:"movil", muscle:"Flexor Cadera",     equip:"Peso corporal"},
  {id:"hipm4",  name:"Mariposa Dinámica",     nameEn:"Dynamic Butterfly",         pattern:"movil", muscle:"Aductores/Cadera",  equip:"Peso corporal"},
  // MOVILIDAD HOMBROS
  {id:"shom1",  name:"Rot. Hombro Banda",     nameEn:"Band Shoulder Rotation",    pattern:"movil", muscle:"Manguito Rotador",  equip:"Banda"},
  {id:"shom2",  name:"Dislocaciones Banda",   nameEn:"Band Dislocations",         pattern:"movil", muscle:"Hombro/Dorsal",     equip:"Banda"},
  {id:"shom3",  name:"Pass Through Palo",     nameEn:"Shoulder Pass Through",     pattern:"movil", muscle:"Hombro/Pecho",      equip:"Palo/Banda"},
  {id:"shom4",  name:"Apertura Pecho Banda",  nameEn:"Band Chest Opener",         pattern:"movil", muscle:"Pecho/Hombro",      equip:"Banda"},
  // MOVILIDAD TOBILLO
  {id:"ankm1",  name:"Movilidad Tobillo Pared", nameEn:"Ankle Wall Mobility",     pattern:"movil", muscle:"Tobillo/Pantorrilla", equip:"Peso corporal"},
  {id:"ankm2",  name:"Tobillo Banda",         nameEn:"Band Ankle Mobilization",   pattern:"movil", muscle:"Tobillo",           equip:"Banda"},
  {id:"ankm3",  name:"Círculos Tobillo",      nameEn:"Ankle Circles",             pattern:"movil", muscle:"Tobillo",           equip:"Peso corporal"},
  {id:"ankm4",  name:"Sentadilla Tobillo",    nameEn:"Ankle Squat Stretch",       pattern:"movil", muscle:"Tobillo/Pantorrilla", equip:"Peso corporal"},
  // CORE ISOMETRICO
  {id:"plank2", name:"Plancha Lateral",      nameEn:"Side Plank",              pattern:"core", muscle:"Oblicuos",           equip:"Peso corporal"},
  {id:"plank3", name:"Plancha RKC",          nameEn:"RKC Plank",               pattern:"core", muscle:"Core completo",      equip:"Peso corporal"},
  {id:"hollow", name:"Hollow Hold",          nameEn:"Hollow Hold",             pattern:"core", muscle:"Abdominales/Core",   equip:"Peso corporal"},
  {id:"abwheel",name:"Rueda Abdominal",      nameEn:"Ab Wheel Rollout",        pattern:"core", muscle:"Core/Dorsal",        equip:"Rueda ab"},
  {id:"renegade",name:"Remo Renegado",       nameEn:"Renegade Row",            pattern:"core", muscle:"Core/Dorsal/Triceps", equip:"Mancuernas"},
  {id:"tgu",     name:"Levantada Turca",     nameEn:"Turkish Get-Up",          pattern:"core", muscle:"Core/Hombro/Cadera",  equip:"Kettlebell"},
  {id:"remoren",name:"Remo Renegado",        nameEn:"Renegade Row",            pattern:"core", muscle:"Core/Dorsal/Biceps",  equip:"Mancuernas"},
  {id:"tgu",    name:"TGU Levantada Turca",  nameEn:"Turkish Get-Up",          pattern:"core", muscle:"Core/Hombro/Cadera",  equip:"Kettlebell"},
  {id:"deadbug", name:"Dead Bug",            nameEn:"Dead Bug",                pattern:"core", muscle:"Core/Estabilización",equip:"Peso corporal"},
  {id:"pallof", name:"Pallof Press",         nameEn:"Pallof Press",            pattern:"core", muscle:"Anti-rotación Core", equip:"Banda/Polea"},
  // CORE DINAMICO
  {id:"mtnclmb",name:"Mountain Climber",     nameEn:"Mountain Climber",        pattern:"core", muscle:"Core/Cardio",        equip:"Peso corporal"},
  {id:"vup",    name:"V-Up",                 nameEn:"V-Up",                    pattern:"core", muscle:"Abdominales",        equip:"Peso corporal"},
  {id:"russtwist",name:"Russian Twist",      nameEn:"Russian Twist",           pattern:"core", muscle:"Oblicuos",           equip:"Disco/Mancuerna"},
  {id:"situp",  name:"Sit-Up",              nameEn:"Sit-Up",                   pattern:"core", muscle:"Abdominales",        equip:"Peso corporal"},
  {id:"tobar",  name:"Toes to Bar",          nameEn:"Toes to Bar",             pattern:"core", muscle:"Core/Flexores",      equip:"Barra fija"},
  {id:"woodchop",name:"Hacha con Banda",     nameEn:"Band Woodchop",           pattern:"core", muscle:"Oblicuos/Core",      equip:"Banda/Polea"},
  {id:"dragoncurl",name:"Dragon Flag",       nameEn:"Dragon Flag",             pattern:"core", muscle:"Core completo",      equip:"Banco"},
  {id:"bgoodmorn",name:"Buenos Dias Banda",  nameEn:"Band Good Morning",       pattern:"core", muscle:"Lumbar/Core",        equip:"Banda"},
  // BICEPS
  {id:"curlconc",  name:"Curl Concentrado",  nameEn:"Concentration Curl",   pattern:"traccion", muscle:"Bíceps",           equip:"Mancuerna"},
  {id:"curlpolea", name:"Curl en Polea",      nameEn:"Cable Curl",           pattern:"traccion", muscle:"Bíceps",           equip:"Polea"},
  {id:"curlw",     name:"Curl Barra W",       nameEn:"EZ Bar Curl",          pattern:"traccion", muscle:"Bíceps/Braquial",  equip:"Barra W"},
  // TRICEPS
  {id:"kickback",  name:"Patada de Burro",    nameEn:"Triceps Kickback",     pattern:"empuje",   muscle:"Tríceps",          equip:"Mancuerna"},
  // HOMBROS
  {id:"rearfly",   name:"Vuelos Post. Banco", nameEn:"Rear Delt Fly Bench",  pattern:"traccion", muscle:"Hombro Posterior", equip:"Mancuernas"},
  // ESPALDA
  {id:"pendlay",   name:"Remo Pendlay",       nameEn:"Pendlay Row",          pattern:"traccion", muscle:"Dorsal/Trapecio",  equip:"Barra"},
  {id:"serrucho",  name:"Remo Serrucho",      nameEn:"One Arm DB Row",       pattern:"traccion", muscle:"Dorsal",           equip:"Mancuerna"},
  {id:"remoalto",  name:"Remo Alto Polea",    nameEn:"Cable High Row",       pattern:"traccion", muscle:"Dorsal/Bíceps",    equip:"Polea"},
  // HOMBROS adicionales
  {id:"frontfly",  name:"Vuelos Frontales",      nameEn:"Front Raise",             pattern:"empuje",   muscle:"Hombro Anterior",  equip:"Mancuernas"},
  {id:"pushunil",  name:"Press Unilat. Arrod.",  nameEn:"Kneeling 1-Arm Press",    pattern:"empuje",   muscle:"Hombro/Core",       equip:"Mancuerna"},
  {id:"pressunil", name:"Press Unilat. De Pie",  nameEn:"Standing 1-Arm Press",    pattern:"empuje",   muscle:"Hombro/Core",       equip:"Mancuerna"},
  {id:"pushpress", name:"Push Press",             nameEn:"Push Press",              pattern:"empuje",   muscle:"Hombro/Piernas",    equip:"Barra"},
  // PIERNAS adicionales
  {id:"stepup",    name:"Step Up",                nameEn:"Step Up",                 pattern:"pierna",   muscle:"Cuadriceps/Glúteo", equip:"Banco/Mancuernas"},
  {id:"lstepup",   name:"Lateral Step Up",        nameEn:"Lateral Step Up",         pattern:"pierna",   muscle:"Glúteo/Abductores", equip:"Banco"},
  // CORE adicionales
  {id:"espinales", name:"Espinales",              nameEn:"Back Extensions",         pattern:"core",     muscle:"Lumbar",            equip:"Banco romano"},
  {id:"revolcase", name:"Revolver la Olla",       nameEn:"Stir the Pot",            pattern:"core",     muscle:"Core completo",     equip:"Fitball"},
  {id:"pallofkn",  name:"Pallof Press Arrod.",    nameEn:"Kneeling Pallof Press",   pattern:"core",     muscle:"Anti-rot. Core",    equip:"Banda/Polea"},
  {id:"rollout",   name:"Roll Out Fitball",       nameEn:"Fitball Rollout",         pattern:"core",     muscle:"Core/Dorsal",       equip:"Fitball"},
  {id:"deadbugd",  name:"Dead Bug con Disco",     nameEn:"Dead Bug with Plate",     pattern:"core",     muscle:"Core/Estabilización",equip:"Disco"},
  // ESPALDA adicionales
  {id:"pullover",  name:"Pull Over Polea",        nameEn:"Cable Pullover",          pattern:"traccion", muscle:"Dorsal/Pecho",      equip:"Polea"},
  // PIERNAS/GLÚTEO adicionales
  {id:"deadasim",  name:"PM Asimétrico",         nameEn:"Asymmetric Deadlift",     pattern:"pierna",   muscle:"Isquios/Glúteo/Core", equip:"Mancuerna/Disco"},
  {id:"deadunil",  name:"PM Una Pierna",          nameEn:"Single Leg Deadlift",     pattern:"pierna",   muscle:"Isquios/Glúteo",      equip:"Mancuerna/Barra"},
  {id:"kbswing",   name:"KB Swing",               nameEn:"Kettlebell Swing",        pattern:"pierna",   muscle:"Glúteo/Isquios/Core", equip:"Kettlebell"},
  {id:"glutepolea",name:"Patada Glúteo Polea",    nameEn:"Cable Glute Kickback",    pattern:"pierna",   muscle:"Glúteo",              equip:"Polea"},
  {id:"abduccion", name:"Abducción Máquina",      nameEn:"Hip Abduction Machine",   pattern:"pierna",   muscle:"Abductores/Glúteo",   equip:"Máquina"},
  {id:"aduccion",  name:"Aducción Máquina",       nameEn:"Hip Adduction Machine",   pattern:"pierna",   muscle:"Aductores",           equip:"Máquina"},
  {id:"nordicos",  name:"Nórdicos",               nameEn:"Nordic Curls",            pattern:"pierna",   muscle:"Isquios",             equip:"Banco/Pareja"},
  // FUNCIONALES
  {id:"farmerw",   name:"Caminata del Granjero",  nameEn:"Farmer's Walk",           pattern:"core",     muscle:"Core/Trapecios/Grip", equip:"Mancuernas/Discos"},
  {id:"farmerwu",  name:"Granjero Unilateral",    nameEn:"Suitcase Carry",          pattern:"core",     muscle:"Core Anti-lat./Grip", equip:"Mancuerna/Disco"},
  {id:"trxrow",    name:"Remo en TRX",            nameEn:"TRX Row",                 pattern:"traccion", muscle:"Dorsal/Bíceps/Core",  equip:"TRX"},
  {id:"bulgsq",   name:"Sentadilla Búlgara",   nameEn:"Bulgarian Split Squat",  pattern:"pierna",  muscle:"Cuadriceps/Glúteo",  equip:"Mancuernas/Barra"},
  {id:"cablefly", name:"Cruces Polea Alta",     nameEn:"Cable Crossover High",   pattern:"empuje",  muscle:"Pecho",              equip:"Polea"},
  // OLÍMPICOS
  {id:"clean",    name:"Clean",              nameEn:"Power Clean",         pattern:"oly", muscle:"Full Body/Explosivo",  equip:"Barra"},
  {id:"snatch",   name:"Arrancada",           nameEn:"Snatch",              pattern:"oly", muscle:"Full Body/Explosivo",  equip:"Barra"},
  {id:"cleanjerk",name:"Envión",              nameEn:"Clean & Jerk",        pattern:"oly", muscle:"Full Body/Explosivo",  equip:"Barra"},
  {id:"hangclean",name:"Colgante Clean",      nameEn:"Hang Clean",          pattern:"oly", muscle:"Isquios/Trap/Hombro",  equip:"Barra"},
  {id:"pushpress2",name:"Push Jerk",          nameEn:"Push Jerk",           pattern:"oly", muscle:"Hombro/Tríceps/Pierna",equip:"Barra"},
  {id:"cleanpull",name:"Tirón de Clean",      nameEn:"Clean Pull",          pattern:"oly", muscle:"Espalda/Isquios/Trap", equip:"Barra"},
  // CARDIO
  {id:"soga",     name:"Saltar la Soga",    nameEn:"Jump Rope",           pattern:"cardio", muscle:"Cardiovascular/Pantorrillas", equip:"Soga"},
  {id:"bici",     name:"Bicicleta",         nameEn:"Stationary Bike",     pattern:"cardio", muscle:"Cardiovascular/Piernas",      equip:"Bicicleta"},
  {id:"cinta",    name:"Cinta",             nameEn:"Treadmill Walk",      pattern:"cardio", muscle:"Cardiovascular",              equip:"Cinta"},
  {id:"trote",    name:"Trote en Cinta",    nameEn:"Treadmill Run",       pattern:"cardio", muscle:"Cardiovascular/Piernas",      equip:"Cinta"},
  {id:"eliptico", name:"Eliptico",          nameEn:"Elliptical",          pattern:"cardio", muscle:"Cardiovascular/Cuerpo completo", equip:"Eliptico"},
  // RODILLA DOMINANTE (nuevos IDs)
  {id:"bulgsplit",name:"Bulgarian Split Squat", nameEn:"Bulgarian Split Squat", pattern:"rodilla", muscle:"Cuadriceps/Gluteo", equip:"Mancuernas/Barra"},
];

// Videos de YouTube por ejercicio ID
export const VIDEOS = {
  "sq":    "https://youtu.be/-bJIpOq-LWk",
  "lp":    "https://www.youtube.com/results?search_query=prensa+piernas+tecnica+shorts",
  "lunge": "https://www.youtube.com/results?search_query=zancada+tecnica+tutorial+shorts",
  "dl":    "https://www.youtube.com/results?search_query=peso+muerto+tecnica+tutorial+shorts",
  "rdl":   "https://www.youtube.com/results?search_query=peso+muerto+rumano+tecnica+shorts",
  "hcurl": "https://www.youtube.com/results?search_query=curl+femoral+tecnica+shorts",
  "hip":   "https://www.youtube.com/results?search_query=hip+thrust+tecnica+tutorial+shorts",
  "calf":  "https://www.youtube.com/results?search_query=pantorrillas+gemelos+tecnica+shorts",
  "bp":    "https://www.youtube.com/results?search_query=press+banca+tecnica+tutorial+shorts",
  "ibp":   "https://www.youtube.com/results?search_query=press+inclinado+banca+tecnica+shorts",
  "dbp":   "https://www.youtube.com/results?search_query=press+mancuernas+pecho+tecnica+shorts",
  "fly":   "https://www.youtube.com/results?search_query=aperturas+pecho+mancuernas+tecnica+shorts",
  "ohp":   "https://www.youtube.com/results?search_query=press+militar+hombros+tecnica+shorts",
  "late":  "https://www.youtube.com/results?search_query=elevaciones+laterales+hombro+tecnica+shorts",
  "dip":   "https://www.youtube.com/results?search_query=fondos+paralelas+triceps+tecnica+shorts",
  "tpush": "https://www.youtube.com/results?search_query=extension+triceps+polea+tecnica+shorts",
  "pu":    "https://www.youtube.com/results?search_query=dominadas+tecnica+tutorial+shorts",
  "row":   "https://www.youtube.com/results?search_query=remo+barra+espalda+tecnica+shorts",
  "crow":  "https://www.youtube.com/results?search_query=remo+polea+cable+tecnica+shorts",
  "lat":   "https://www.youtube.com/results?search_query=jalon+pecho+dorsal+tecnica+shorts",
  "facep": "https://www.youtube.com/results?search_query=face+pull+hombro+posterior+tecnica+shorts",
  "curl":  "https://www.youtube.com/results?search_query=curl+biceps+mancuernas+tecnica+shorts",
  "plank": "https://www.youtube.com/results?search_query=plancha+core+tecnica+tutorial+shorts",
  "crunch":"https://www.youtube.com/results?search_query=crunch+abdominal+tecnica+shorts",
  "legr":  "https://www.youtube.com/results?search_query=elevacion+piernas+abdominales+tecnica+shorts",
  "mob1":  "https://www.youtube.com/results?search_query=movilidad+cadera+ejercicios+shorts",
  "mob2":  "https://www.youtube.com/results?search_query=movilidad+toracica+columna+ejercicios+shorts",
  "suppu": "https://www.youtube.com/results?search_query=dominadas+supinas+chin+up+tecnica+shorts",
  "hammer":"https://www.youtube.com/results?search_query=curl+martillo+biceps+tecnica+shorts",
  "legcurl":"https://www.youtube.com/results?search_query=sillon+isquios+curl+femoral+maquina+shorts",
  "legext":"https://www.youtube.com/results?search_query=sillon+cuadriceps+extension+maquina+shorts",
  "trico": "https://www.youtube.com/results?search_query=triceps+polea+pushdown+tecnica+shorts",
  "lateralfly":"https://www.youtube.com/results?search_query=vuelos+laterales+hombro+tecnica+shorts",
  "trot1": "https://www.youtube.com/results?search_query=rotacion+toracica+suelo+movilidad+shorts",
  "trot2": "https://www.youtube.com/results?search_query=rotacion+toracica+cuadrupedia+movilidad+shorts",
  "trot3": "https://www.youtube.com/results?search_query=foam+roller+columna+toracica+movilidad+shorts",
  "trot4": "https://www.youtube.com/results?search_query=rotacion+toracica+banda+elastica+shorts",
  "hipm1": "https://www.youtube.com/results?search_query=90+90+movilidad+cadera+ejercicio+shorts",
  "hipm2": "https://www.youtube.com/results?search_query=apertura+cadera+banda+elastica+movilidad+shorts",
  "hipm3": "https://www.youtube.com/results?search_query=estocada+movilidad+cadera+flexor+shorts",
  "hipm4": "https://www.youtube.com/results?search_query=mariposa+dinamica+aductores+cadera+shorts",
  "shom1": "https://www.youtube.com/results?search_query=rotacion+hombro+banda+manguito+rotador+shorts",
  "shom2": "https://www.youtube.com/results?search_query=dislocaciones+hombro+banda+movilidad+shorts",
  "shom3": "https://www.youtube.com/results?search_query=pass+through+palo+movilidad+hombros+shorts",
  "shom4": "https://www.youtube.com/results?search_query=apertura+pecho+banda+hombros+movilidad+shorts",
  "ankm1": "https://www.youtube.com/results?search_query=movilidad+tobillo+pared+ejercicio+shorts",
  "ankm2": "https://www.youtube.com/results?search_query=movilidad+tobillo+banda+elastica+shorts",
  "ankm3": "https://www.youtube.com/results?search_query=circulos+tobillo+movilidad+shorts",
  "ankm4": "https://www.youtube.com/results?search_query=sentadilla+tobillo+movilidad+shorts",
  "plank2":  "https://www.youtube.com/results?search_query=plancha+lateral+oblicuos+tecnica+shorts",
  "plank3":  "https://www.youtube.com/results?search_query=RKC+plank+tecnica+core+shorts",
  "hollow":  "https://www.youtube.com/results?search_query=hollow+hold+abdominales+tecnica+shorts",
  "abwheel": "https://www.youtube.com/results?search_query=rueda+abdominal+rollout+tecnica+shorts",
  "deadbug": "https://www.youtube.com/results?search_query=dead+bug+core+estabilizacion+shorts",
  "pallof":  "https://www.youtube.com/results?search_query=pallof+press+core+anti+rotacion+shorts",
  "mtnclmb": "https://www.youtube.com/results?search_query=mountain+climber+core+cardio+tecnica+shorts",
  "vup":     "https://www.youtube.com/results?search_query=v+up+abdominales+tecnica+shorts",
  "russtwist":"https://www.youtube.com/results?search_query=russian+twist+oblicuos+tecnica+shorts",
  "situp":   "https://www.youtube.com/results?search_query=sit+up+abdominales+tecnica+shorts",
  "tobar":   "https://www.youtube.com/results?search_query=toes+to+bar+core+tecnica+shorts",
  "woodchop":"https://www.youtube.com/results?search_query=hacha+banda+oblicuos+woodchop+shorts",
  "dragoncurl":"https://www.youtube.com/results?search_query=dragon+flag+core+avanzado+shorts",
  "bgoodmorn":"https://www.youtube.com/results?search_query=buenos+dias+banda+lumbar+core+shorts",
  "curlconc": "https://www.youtube.com/results?search_query=curl+concentrado+biceps+tecnica+shorts",
  "curlpolea":"https://www.youtube.com/results?search_query=curl+biceps+polea+cable+tecnica+shorts",
  "curlw":    "https://www.youtube.com/results?search_query=curl+barra+w+ez+biceps+tecnica+shorts",
  "kickback": "https://www.youtube.com/results?search_query=patada+burro+triceps+mancuerna+tecnica+shorts",
  "rearfly":  "https://www.youtube.com/results?search_query=vuelos+posteriores+banco+hombro+tecnica+shorts",
  "pendlay":  "https://www.youtube.com/results?search_query=remo+pendlay+barra+tecnica+shorts",
  "serrucho": "https://www.youtube.com/results?search_query=remo+serrucho+mancuerna+espalda+tecnica+shorts",
  "remoalto": "https://www.youtube.com/results?search_query=remo+alto+polea+cable+espalda+tecnica+shorts",
};

// Imagenes de referencia por ejercicio ID
export const IMGS = {
  "sq":    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Squats.png/320px-Squats.png",
  "lp":    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Leg_press.jpg/320px-Leg_press.jpg",
  "lunge": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Lunges.jpg/320px-Lunges.jpg",
  "dl":    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Deadlift_form.jpg/320px-Deadlift_form.jpg",
  "rdl":   "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Romanian_deadlift.jpg/320px-Romanian_deadlift.jpg",
  "hcurl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Leg_curl.jpg/320px-Leg_curl.jpg",
  "hip":   "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Hip_thrust.jpg/320px-Hip_thrust.jpg",
  "calf":  "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Calf_raise.jpg/320px-Calf_raise.jpg",
  "bp":    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Bench_press_2.jpg/320px-Bench_press_2.jpg",
  "ibp":   "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Incline_bench_press.jpg/320px-Incline_bench_press.jpg",
  "dbp":   "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Dumbbell_bench_press.jpg/320px-Dumbbell_bench_press.jpg",
  "fly":   "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Dumbbell_fly.jpg/320px-Dumbbell_fly.jpg",
  "ohp":   "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Overhead_press.jpg/320px-Overhead_press.jpg",
  "late":  "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Lateral_raise.jpg/320px-Lateral_raise.jpg",
  "dip":   "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Dips_on_a_chair.jpg/320px-Dips_on_a_chair.jpg",
  "tpush": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Triceps_pushdown.jpg/320px-Triceps_pushdown.jpg",
  "pu":    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Pull_up_demonstration.jpg/320px-Pull_up_demonstration.jpg",
  "row":   "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Bent_over_row.jpg/320px-Bent_over_row.jpg",
  "crow":  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Seated_cable_row.jpg/320px-Seated_cable_row.jpg",
  "lat":   "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Lat_pulldown.jpg/320px-Lat_pulldown.jpg",
  "facep": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Face_pull.jpg/320px-Face_pull.jpg",
  "curl":  "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Dumbbell_curl.jpg/320px-Dumbbell_curl.jpg",
  "plank": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Plank_position.jpg/320px-Plank_position.jpg",
  "crunch":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Abdominal_crunch.jpg/320px-Abdominal_crunch.jpg",
  "legr":  "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Leg_raise.jpg/320px-Leg_raise.jpg",
  "mob1":  "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Hip_flexor_stretch.jpg/320px-Hip_flexor_stretch.jpg",
  "mob2":  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Thoracic_rotation.jpg/320px-Thoracic_rotation.jpg",
};
